name: Update Firestore data

on:
  push:
    branches:
      - github-action
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo $SERVICE_ACCOUNT_JSON > serviceAccount.json
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      - run: ./scripts/copy-data.main.kts data/database/*
